import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Blog a insighty | Firemni rentgen",
    description:
        "Prakticke clanky pro majitele a reditele malych a strednich firem. Jak odhalit ztraty, pretizeny tym a chaos v procesech.",
          alternates: {
              canonical: "https://www.flowlens.cz/blog",
                },
                };

                const articles = [
                  {
                      slug: "kde-firmy-ztraci-penize",
                          title: "5 mist, kde firmy nejcasteji ztraci penize",
                              perex:
                                    "Vetsina firem ztraci penize na mistech, kde to vubec necekaji. Tady je pet oblasti, ktere by mel zkontrolovat kazdy majitel firmy.",
                                        date: "2026-05-13",
                                          },
                                            {
                                                slug: "pretizeny-tym",
                                                    title: "Jak poznat pretizeny tym driv, nez zacne nestihat",
                                                        perex:
                                                              "Pretizeni zamestnanci nezacnou najednou. Zacina to pomalu — zpozdenymi ukoly, chybami, poklesem kvality. Jak to rozpoznat vcas?",
                                                                  date: "2026-05-13",
                                                                    },
                                                                      {
                                                                          slug: "chaos-v-pozadavcich",
                                                                              title: "Proc vetsina firem netusi, kolik stoji chaos v pozadavcich",
                                                                                  perex:
                                                                                        "Nerizene pozadavky, duplicitni ukoly, neproritizovana prace. Tichy zabijecky efektivity, ktere firma nezaznamena — az do chvile, kdy je pozde.",
                                                                                            date: "2026-05-13",
                                                                                              },
                                                                                              ];

                                                                                              export default function BlogPage() {
                                                                                                return (
                                                                                                    <main className="min-h-screen bg-slate-950 text-white px-5 py-16">
                                                                                                          <div className="max-w-3xl mx-auto">
                                                                                                                  <div className="mb-4 text-blue-400 text-sm font-bold uppercase tracking-wider">
                                                                                                                            Clanky a insighty
                                                                                                                                    </div>
                                                                                                                                            <h1 className="text-4xl font-black mb-4">
                                                                                                                                                      Co se deje ve firmach
                                                                                                                                                              </h1>
                                                                                                                                                                      <p className="text-slate-400 text-lg mb-12">
                                                                                                                                                                                Prakticke texty pro majitele a reditele. Bez teorie, jen to, co ve firmach opravdu funguje.
                                                                                                                                                                                        </p>
                                                                                                                                                                                        
                                                                                                                                                                                                <div className="space-y-8">
                                                                                                                                                                                                          {articles.map((article) => (
                                                                                                                                                                                                                      <article
                                                                                                                                                                                                                                    key={article.slug}
                                                                                                                                                                                                                                                  className="border border-slate-800 rounded-lg p-6 hover:border-slate-600 transition-colors"
                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                            <time className="text-slate-500 text-sm">{article.date}</time>
                                                                                                                                                                                                                                                                                          <h2 className="text-xl font-bold mt-2 mb-3">
                                                                                                                                                                                                                                                                                                          <Link
                                                                                                                                                                                                                                                                                                                            href={`/blog/${article.slug}`}
                                                                                                                                                                                                                                                                                                                                              className="hover:text-blue-400 transition-colors"
                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                {article.title}
                                                                                                                                                                                                                                                                                                                                                                                                </Link>
                                                                                                                                                                                                                                                                                                                                                                                                              </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-slate-400 leading-relaxed">{article.perex}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                          <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                          href={`/blog/${article.slug}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="inline-block mt-4 text-blue-400 text-sm hover:text-blue-300 transition-colors"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Cist clanek &rarr;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </article>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="mt-16 pt-8 border-t border-slate-800 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  href="/"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="text-slate-400 hover:text-white transition-colors"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    &larr; Zpet na hlavni stranku
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
